#spring.application.name=flashcards

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

jwt.secret.key=${JWT_SECRET}
spring.ai.openai.api-key=${OPENAI_API_KEY}