#spring.application.name=flashcards

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret.key=${JWT_SECRET}
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.security.oauth2.client.registration.google.client-id = ${CLIENT_ID_GOOGLE}
spring.security.oauth2.client.registration.google.client-secret = ${CLIENT_SECRET_GOOGLE}